# Generated by Django 4.2.2 on 2023-07-22 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_calendarioacademico_prioridad_notificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Prioridad',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.AddField(
            model_name='aula',
            name='disponibilidad',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aula',
            name='institucion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='herramientas',
            name='disponibilidad',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='herramientas',
            name='institucion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='herramientas',
            name='ubicacion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='disponibilidad',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='institucion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aula',
            name='ubicacion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='ubicacion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.CharField(default='11222333', max_length=10, unique=True),
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
