# Generated by Django 4.2.2 on 2023-07-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_notificacion_destinatario_remove_post_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarioacademico',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='calendarioacademico',
            name='franja_horaria',
        ),
        migrations.AddField(
            model_name='calendarioacademico',
            name='fecha_finalizacion',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='calendarioacademico',
            name='fecha_inicio',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='calendarioacademico',
            name='hora_finalizacion',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='calendarioacademico',
            name='hora_inicio',
            field=models.TimeField(default=None),
        ),
    ]
