# Generated by Django 4.2.2 on 2023-07-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_tipo_evento_calendarioacademico_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventocalendario',
            name='calendario',
        ),
        migrations.DeleteModel(
            name='CalendarioAcademico',
        ),
    ]
